# https://docs.readthedocs.io/en/latest/yaml-config.html
# Read the Docs configuration file for Sphinx projects

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.7"

sphinx:
   configuration: docs/conf.py

formats:
    - epub
    - pdf

python:
  install:
    - requirements: requirements/requirements_doc.txt
    - method: pip
