#! /usr/bin/python
# -*- coding: utf-8 -*-

# load nn ops
from tensorlayerx.backend.load_backend import padding_format
from tensorlayerx.backend.load_backend import preprocess_1d_format
from tensorlayerx.backend.load_backend import preprocess_2d_format
from tensorlayerx.backend.load_backend import preprocess_3d_format
from tensorlayerx.backend.load_backend import nchw_to_nhwc
from tensorlayerx.backend.load_backend import nhwc_to_nchw
from tensorlayerx.backend.load_backend import relu
from tensorlayerx.backend.load_backend import elu
from tensorlayerx.backend.load_backend import relu6
from tensorlayerx.backend.load_backend import leaky_relu
from tensorlayerx.backend.load_backend import sigmoid
from tensorlayerx.backend.load_backend import softmax
from tensorlayerx.backend.load_backend import gelu
from tensorlayerx.backend.load_backend import bias_add
from tensorlayerx.backend.load_backend import conv1d
from tensorlayerx.backend.load_backend import conv2d
from tensorlayerx.backend.load_backend import conv3d
from tensorlayerx.backend.load_backend import moments
from tensorlayerx.backend.load_backend import max_pool
from tensorlayerx.backend.load_backend import max_pool3d
from tensorlayerx.backend.load_backend import avg_pool3d
from tensorlayerx.backend.load_backend import pool
from tensorlayerx.backend.load_backend import depthwise_conv2d
from tensorlayerx.backend.load_backend import Conv1d_transpose
from tensorlayerx.backend.load_backend import Conv2d_transpose
from tensorlayerx.backend.load_backend import BinaryConv2D
from tensorlayerx.backend.load_backend import DorefaConv2D
from tensorlayerx.backend.load_backend import lstmcell
from tensorlayerx.backend.load_backend import rnnbase
from tensorlayerx.backend.load_backend import layernorm
from tensorlayerx.backend.load_backend import multiheadattention

from tensorlayerx.backend.load_backend import ReLU
from tensorlayerx.backend.load_backend import ELU
from tensorlayerx.backend.load_backend import ReLU6
from tensorlayerx.backend.load_backend import LeakyReLU
from tensorlayerx.backend.load_backend import Softplus
from tensorlayerx.backend.load_backend import Tanh
from tensorlayerx.backend.load_backend import Sigmoid
from tensorlayerx.backend.load_backend import Softmax
from tensorlayerx.backend.load_backend import GeLU
from tensorlayerx.backend.load_backend import Conv1D
from tensorlayerx.backend.load_backend import Conv3D
from tensorlayerx.backend.load_backend import BiasAdd
from tensorlayerx.backend.load_backend import MaxPool1d
from tensorlayerx.backend.load_backend import MaxPool
from tensorlayerx.backend.load_backend import MaxPool3d
from tensorlayerx.backend.load_backend import AvgPool1d
from tensorlayerx.backend.load_backend import AvgPool
from tensorlayerx.backend.load_backend import AvgPool3d
from tensorlayerx.backend.load_backend import Dropout
from tensorlayerx.backend.load_backend import BatchNorm
from tensorlayerx.backend.load_backend import DepthwiseConv2d
from tensorlayerx.backend.load_backend import SeparableConv1D
from tensorlayerx.backend.load_backend import SeparableConv2D
from tensorlayerx.backend.load_backend import AdaptiveMeanPool2D
from tensorlayerx.backend.load_backend import AdaptiveMeanPool3D
from tensorlayerx.backend.load_backend import AdaptiveMaxPool1D
from tensorlayerx.backend.load_backend import AdaptiveMaxPool2D
from tensorlayerx.backend.load_backend import AdaptiveMaxPool3D
from tensorlayerx.backend.load_backend import Floor
from tensorlayerx.backend.load_backend import Ceil
from tensorlayerx.backend.load_backend import BinaryDense
from tensorlayerx.backend.load_backend import DorefaDense
from tensorlayerx.backend.load_backend import TernaryDense
from tensorlayerx.backend.load_backend import QuanDense
from tensorlayerx.backend.load_backend import QuanDenseBn
from tensorlayerx.backend.load_backend import TernaryConv
from tensorlayerx.backend.load_backend import QuanConv
from tensorlayerx.backend.load_backend import QuanConvBn

# load ops
from tensorlayerx.backend.load_backend import Variable
from tensorlayerx.backend.load_backend import matmul
from tensorlayerx.backend.load_backend import add
from tensorlayerx.backend.load_backend import dtypes
from tensorlayerx.backend.load_backend import minimum
from tensorlayerx.backend.load_backend import concat
from tensorlayerx.backend.load_backend import convert_to_tensor
from tensorlayerx.backend.load_backend import convert_to_numpy
from tensorlayerx.backend.load_backend import reduce_mean
from tensorlayerx.backend.load_backend import reduce_min
from tensorlayerx.backend.load_backend import reduce_max
from tensorlayerx.backend.load_backend import pad
from tensorlayerx.backend.load_backend import stack
from tensorlayerx.backend.load_backend import meshgrid
from tensorlayerx.backend.load_backend import expand_dims
from tensorlayerx.backend.load_backend import tile
from tensorlayerx.backend.load_backend import cast
from tensorlayerx.backend.load_backend import transpose
from tensorlayerx.backend.load_backend import gather_nd
from tensorlayerx.backend.load_backend import clip_by_value
from tensorlayerx.backend.load_backend import split
from tensorlayerx.backend.load_backend import get_tensor_shape
from tensorlayerx.backend.load_backend import set_context
from tensorlayerx.backend.load_backend import resize
from tensorlayerx.backend.load_backend import floor
from tensorlayerx.backend.load_backend import gather
from tensorlayerx.backend.load_backend import linspace
from tensorlayerx.backend.load_backend import add_n
from tensorlayerx.backend.load_backend import multiply
from tensorlayerx.backend.load_backend import identity
from tensorlayerx.backend.load_backend import triu
from tensorlayerx.backend.load_backend import tril
from tensorlayerx.backend.load_backend import abs
from tensorlayerx.backend.load_backend import acos
from tensorlayerx.backend.load_backend import acosh
from tensorlayerx.backend.load_backend import angle
from tensorlayerx.backend.load_backend import argmax
from tensorlayerx.backend.load_backend import argmin
from tensorlayerx.backend.load_backend import asin
from tensorlayerx.backend.load_backend import asinh
from tensorlayerx.backend.load_backend import atan
from tensorlayerx.backend.load_backend import atanh
from tensorlayerx.backend.load_backend import cos
from tensorlayerx.backend.load_backend import cosh
from tensorlayerx.backend.load_backend import count_nonzero
from tensorlayerx.backend.load_backend import cumprod
from tensorlayerx.backend.load_backend import cumsum
from tensorlayerx.backend.load_backend import equal
from tensorlayerx.backend.load_backend import exp
from tensorlayerx.backend.load_backend import floormod
from tensorlayerx.backend.load_backend import greater
from tensorlayerx.backend.load_backend import greater_equal
from tensorlayerx.backend.load_backend import is_inf
from tensorlayerx.backend.load_backend import is_nan
from tensorlayerx.backend.load_backend import l2_normalize
from tensorlayerx.backend.load_backend import less
from tensorlayerx.backend.load_backend import less_equal
from tensorlayerx.backend.load_backend import log
from tensorlayerx.backend.load_backend import log_sigmoid
from tensorlayerx.backend.load_backend import maximum
from tensorlayerx.backend.load_backend import negative
from tensorlayerx.backend.load_backend import not_equal
from tensorlayerx.backend.load_backend import pow
from tensorlayerx.backend.load_backend import real
from tensorlayerx.backend.load_backend import reciprocal
from tensorlayerx.backend.load_backend import reduce_prod
from tensorlayerx.backend.load_backend import reduce_std
from tensorlayerx.backend.load_backend import reduce_sum
from tensorlayerx.backend.load_backend import reduce_variance
from tensorlayerx.backend.load_backend import round
from tensorlayerx.backend.load_backend import rsqrt
from tensorlayerx.backend.load_backend import segment_mean
from tensorlayerx.backend.load_backend import segment_min
from tensorlayerx.backend.load_backend import segment_prod
from tensorlayerx.backend.load_backend import segment_sum
from tensorlayerx.backend.load_backend import sign
from tensorlayerx.backend.load_backend import sin
from tensorlayerx.backend.load_backend import sinh
from tensorlayerx.backend.load_backend import softplus
from tensorlayerx.backend.load_backend import square
from tensorlayerx.backend.load_backend import squared_difference
from tensorlayerx.backend.load_backend import subtract
from tensorlayerx.backend.load_backend import tan
from tensorlayerx.backend.load_backend import tanh
from tensorlayerx.backend.load_backend import any
from tensorlayerx.backend.load_backend import all
from tensorlayerx.backend.load_backend import logical_and
from tensorlayerx.backend.load_backend import logical_not
from tensorlayerx.backend.load_backend import logical_xor
from tensorlayerx.backend.load_backend import argsort
from tensorlayerx.backend.load_backend import bmm
from tensorlayerx.backend.load_backend import where
from tensorlayerx.backend.load_backend import ones_like
from tensorlayerx.backend.load_backend import zeros_like
from tensorlayerx.backend.load_backend import squeeze
from tensorlayerx.backend.load_backend import unsorted_segment_sum
from tensorlayerx.backend.load_backend import unsorted_segment_min
from tensorlayerx.backend.load_backend import unsorted_segment_mean
from tensorlayerx.backend.load_backend import unsorted_segment_max



# dtype
from .load_backend import (DType, float16, float32, float64, int8, int16, int32, int64, uint8, uint16, uint32, uint64, bool, complex64, complex128)
# initlizers
from tensorlayerx.backend.load_backend import (zeros, ones, constant, random_uniform, random_normal, truncated_normal, he_normal, xavier_normal, xavier_uniform)
# backend
from tensorlayerx.backend.load_backend import BACKEND
from tensorlayerx.backend.load_backend import BACKEND_VERSION

from tensorlayerx.backend.load_backend import Reshape
from tensorlayerx.backend.load_backend import ReduceSum
from tensorlayerx.backend.load_backend import ReduceMax
from tensorlayerx.backend.load_backend import ReduceMean
from tensorlayerx.backend.load_backend import OneHot
from tensorlayerx.backend.load_backend import L2Normalize
from tensorlayerx.backend.load_backend import NotEqual
from tensorlayerx.backend.load_backend import Cast
from tensorlayerx.backend.load_backend import ExpandDims
from tensorlayerx.backend.load_backend import CountNonzero
from tensorlayerx.backend.load_backend import FlattenReshape
from tensorlayerx.backend.load_backend import Transpose
from tensorlayerx.backend.load_backend import MatMul
from tensorlayerx.backend.load_backend import Tile
from tensorlayerx.backend.load_backend import Concat
from tensorlayerx.backend.load_backend import ZeroPadding1D
from tensorlayerx.backend.load_backend import ZeroPadding2D
from tensorlayerx.backend.load_backend import ZeroPadding3D
from tensorlayerx.backend.load_backend import Stack
from tensorlayerx.backend.load_backend import Unstack
from tensorlayerx.backend.load_backend import Sign
from tensorlayerx.backend.load_backend import Resize
from tensorlayerx.backend.load_backend import Pad
from tensorlayerx.backend.load_backend import Minimum
from tensorlayerx.backend.load_backend import Meshgrid
from tensorlayerx.backend.load_backend import BatchToSpace
from tensorlayerx.backend.load_backend import DepthToSpace

